name: social_media_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  get_it: ^7.2.0
  get: ^4.6.5
  image_picker: ^0.8.7+4
  profanity_filter: ^2.0.0
  http: ^0.13.5
  firebase_core: ^2.10.0
  google_sign_in: ^6.1.0
  firebase_auth: ^4.4.2
  sizer: ^2.0.15
  google_fonts: ^4.0.3
  dio: ^5.1.1
  firebase_storage: ^11.1.1
  path: ^1.8.2
  share_plus: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/hand_in_hand.png"
  min_sdk_android: 21 

flutter:


  uses-material-design: true


  assets:

    - assets/icons/
    - assets/images/